print ('Buenos dias!')
name = input('What is your name?')
football = input('Which football team do you support?')
player = input('Who is your favourite footballer?')
print ('Gracia! So your name is', name)
print ('You support', football)
print ('Your favourite footballer is', player)
print ('Mucho gusto!')

abs()